[package]
name = "anexpia/syncee"
version = "1.1.2"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"

repository = "https://github.com/anexpia/syncee"

description = "A data replication library for easy & flexible server to client replication."

realm = "shared"

# exclude = ["**"]
# include = [
#     "src/**",
#     "LICENSE",
#     "wally.toml",
# ]

[dependencies]
squish = "anexpia/squish@6.1.3"