[package]
name = "anexpia/syncee"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"

description = "A high-performance, flexible, optionally schema-driven one-way data replication library for Roblox."

realm = "shared"

# exclude = ["**"]
# include = [
#     "src/**",
#     "LICENSE",
#     "wally.toml",
# ]

[dependencies]