[package]
name = "anexpia/squish"
version = "6.0.1"
registry = "https://github.com/UpliftGames/wally-index"
licence = "MIT"

description = "Fork of 'Squash' with more features, optimizations, and design changes."

realm = "shared"

# exclude = ["**"]
# include = [
#     "src/**",
#     "LICENSE",
#     "wally.toml",
# ]

[dependencies]